### ISSUE TITLE
pod 导入失败

### ISSUE THREAD

**Issue by lisen1993** [AlfredZY/AZTools#1]
$ pod install
Analyzing dependencies
[!] Unable to find a specification for `AZCategory`

[!] Automatically assigning platform `ios` with version `11.0` on target `YiJie_Doctor` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by AlfredZY** [comment]
可尝试执行 `pod update`
